### PR TITLE
Add canonical format to capnp convert

### PR DESCRIPTION
**Pull request by zombiezen**

### CODE REVIEW

**Comment by kentonv** [comment]
Nice!

You'll need to update the plausibility checks (as Travis caught). Reusing the "flat" checks should be fine; no need to check for canonical ordering.

**Comment by zombiezen** [comment]
Done.

Is it okay that I'm not checking the input being canonical?

**Comment by kentonv** [comment]
Good question. Arguably if someone specifies canonical input instead of flat input, they might want it to be verified. Maybe throw in right after the `SegmentArrayMessageBuilder` declaration:

    if (convertFrom == Format::CANONICAL) {
      KJ_REQUIRE(message.isCanonical());
    }

**Comment by zombiezen** [comment]
Done.

**Comment by kentonv** [comment]
Thanks!

**Pull request merged**
