### PR TITLE
Fix MSVC CI build.

### PR DESCRIPTION
**Pull request by kentonv**
I guess we depended on a vulnerability, lol.

### CODE REVIEW

**Comment by kentonv** [comment]
Well I think I fixed the add-path error but now there's some cmake error I don't understand?

**Comment by harrishancock** [comment]
The CMake error looks like collateral damage:
```
D:\a\capnproto\capnproto\c++\src\kj\exception.c++(1176,8): error C2065: 'ssize_t': undeclared identifier [D:\a\capnproto\capnproto\build-output\src\kj\kj.vcxproj]
D:\a\capnproto\capnproto\c++\src\kj\exception.c++(1176,16): error C2146: syntax error: missing ';' before identifier 'i' [D:\a\capnproto\capnproto\build-output\src\kj\kj.vcxproj]
D:\a\capnproto\capnproto\c++\src\kj\exception.c++(1176,18): error C2143: syntax error: missing ';' before '=' [D:\a\capnproto\capnproto\build-output\src\kj\kj.vcxproj]
D:\a\capnproto\capnproto\c++\src\kj\exception.c++(1176,18): error C2143: syntax error: missing ')' before '=' [D:\a\capnproto\capnproto\build-output\src\kj\kj.vcxproj]
D:\a\capnproto\capnproto\c++\src\kj\exception.c++(1176,18): error C2059: syntax error: '=' [D:\a\capnproto\capnproto\build-output\src\kj\kj.vcxproj]
```
Maybe the new GitHub Actions windows-latest image included a new version of VS2019 that changed some headers.

**Comment by harrishancock** [comment]
Oh, probably more likely is that the new exception iterator code wasn't tested on windows-latest because the action was broken due to the add-path thing.

**Review by harrishancock — APPROVED** [review]

**Comment by kentonv** [comment]
Ugh it's so hard to see the actual errors in these logs. I was looking at the end of the build and wondering why it was reporting errors like "can't find project file" and skipping the tests for no apparent reason.

I'm confused, though. This PR explicitly does not include the recent `exception.c++` changes. I guess the CI is merging the PR with master before testing. I can never understand why CIs do that -- it means the results depend on the state of master at the exact time the tests ran, making them hard to reproduce. Ugh.

Anyway... I guess I'll rebase and then fix that.

**Pull request merged**
