### PR TITLE
Minor package-lint fixes to elisp

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Required fixes to allow upload to melpa https://github.com/melpa/melpa/pull/7613

### CODE REVIEW

**Comment by kentonv** [comment]
Hmm I don't know anything about emacs. It looks like @netguy204 is the original author of these files. @netguy204, do you have thoughts on this?

@tmcgilchrist, note that #1264 also edits these files and was posted a couple days before your PR... weird coincidence?

**Comment by tmcgilchrist** [comment]
Coincidence I think, I wanted to add this mode into `ELPA` and needed these few fixes before it would be accepted. 
https://github.com/capnproto/capnproto/pull/1264 won't pass the `ELPA` linting but looks a useful addition on top of my changes.

**Comment by syohex** [comment]
```lisp
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.capnp\\'" . capnp-mode))
````

I suppose adding above snippet is better for users how about ?

**Comment by tmcgilchrist** [comment]
@syohex Added the autoload section from https://github.com/capnproto/capnproto/pull/1264

Working for me locally and it passes the MELPA validations.
Please confirm and merge when you're ready @kentonv

**Comment by kentonv** [comment]
Whelp, since the original author hasn't responded, and I don't have any other ideas who should review this, I'm just going to take it on trust I guess!

**Comment by kentonv** [comment]
Thanks for the (presumably) improvements! :)

**Pull request merged**
