### PR TITLE
Do not use execinfo.h with uclibc

### PR DESCRIPTION
**Pull request by sonologic**
Fix for #510

### CODE REVIEW

**Comment by kentonv** [comment]
Hi Koen,

Cap'n Proto has three different build systems -- autotools, cmake, and ekam. If we're going to introduce a config.h, they will all need to support performing these checks, or in the absence of checks we'll need to default to the previous behavior. Currently, your change will disable backtraces for cmake and ekam users, which would be pretty disruptive to those of us using those build systems.

In what context are you finding that execinfo.h is missing? Can we extend the `#if` to check for that context without adding a config-time check?

Or maybe we can use the new `__has_include()` preprocessor feature to ask the compiler if the header exists? This feature is supported by GCC (at least back to 4.9) and Clang (forever), and can itself be checked for using `#ifdef __has_include`.

**Comment by sonologic** [comment]
Hi,

Sorry, I wasn't aware that there were three build systems with capnproto. Obviously my pr is not going to float then.

We can add check whether __UCLIBC__ is not defined, something like this:

#if ((__linux__ && __GLIBC__) || __APPLE__) && not defined(__UCLIBC__)

Which is quite ugly, but works.

If that is acceptable to you though, i'll change my pr.

Could also do it with __has_include, and default to including execinfo.h if __has_include is not defined. Personally, i'd prefer the __UCLIBC__ solution above though.

Let me know.

The context btw is that i'm cross-compiling capnproto with buildroot for use on a target with uclibc.

**Comment by kentonv** [comment]
Checking for `__UCLIBC__` sounds fine to me. Thanks!

**Comment by kentonv** [comment]
Hmm, since uclibc appears to be Linux-specific, could this be simplified to:

    #if (__linux__ && __GLIBC__ && !__UCLIBC__) || __APPLE__

?

**Comment by sonologic** [comment]
I think that is a valid approach, yes :)

**Comment by kentonv** [comment]
Merged. Thanks!

**Pull request merged**
