### PR TITLE
Website: Add link to RPC Tracer

### PR DESCRIPTION
**Pull request by t-kondo-tmc**
Hi, thank you for the project.

I'd like to propose adding link to [Cap'n Proto RPC Tracer](https://github.com/toyota-digital-cockpit-pf/capnp-trace) in Tools section.

[Cap'n Proto RPC Tracer](https://github.com/toyota-digital-cockpit-pf/capnp-trace) can trace Cap'n Proto RPC like `strace` command.
Roughly speaking, this tool sniffs Unix Domain Socket communication by `ptrace` and `process_vm_readv`,
and deserialize it with `capnp::SchemaLoader`.
I believe this tool can be useful for Cap'n Proto users.

### CODE REVIEW

**Comment by t-kondo-tmc** [comment]
Hi @kentonv
This is my first contribution, so if I had any deficiencies, please let me know.
Thanks!

**Comment by kentonv** [comment]
Sorry for the delay. The Cap'n Proto web site is not as automated as it should be so I have to do a little work to push it and I was failing to find time, but I'm going to do that now.

This needs to target the `master` branch but I'll cherry-pick in there for you.

**Comment by kentonv** [comment]
This is live. Thanks for building this!

**Comment by t-kondo-tmc** [comment]
@kentonv 
Thank you so much for your graceful support and merge!
Now I've been able to see the link in [the Cap'n Proto web site](https://capnproto.org/otherlang.html)! :tada:

**Pull request merged**
