### PR TITLE
Promise<T> kj::raceSuccessful(kj::Array<T> promises)

### PR DESCRIPTION
**Pull request by mikea**
Executes multiple promises and returns the first successuful result, canceling the rest.
In case of every promise failing fails with the last (in time) error.

### CODE REVIEW

**Comment by mikea** [comment]
I don't think I missed the already existing method, have I?

**Comment by kentonv** [comment]
I guess this is the same as `exclusiveJoin()` except it takes an arbitrary-sized array?

Technically you could implement it by chaining a bunch of `exclusiveJoin()`s together?

**Comment by kentonv** [comment]
Oh I see, it does not immediately propagate rejected promises, unless they _all_ reject?

That seems unusual requirement to me. Every use case I've ever encountered, I wanted to propagate the first failure. What is the use case for this exactly?

I think this is not the obvious expected behavior for a function called `racePromises`, so I'd probably call it something like `racePromisesIgnoreFailures` or `racePromisesFailSlow` (it's the opposite of "fail-fast").

Also while I agree the word "race" is better than "exclusiveJoin", it seems confusing to introduce a new term to mean the same thing. Maybe we should actually rename `exclusiveJoin` to `raceWith`?

**Comment by mikea** [comment]
> That seems unusual requirement to me. Every use case I've ever encountered, I wanted to propagate the first failure. What is the use case for this exactly?

Reading from multiple storage buckets and taking the fastest. One obviously doesn't want to fail if first request to resolve was unsuccessful. 

Happy to change the name.

**Comment by mikea** [comment]
> Maybe we should actually rename exclusiveJoin to raceWith?

I am all for this disregarding our decision in this PR: current name is too confusing. 

I'll create a PR.

**Review by kentonv — APPROVED** [review]
Vaguely feels like if all the promises fail, it should be the first error that gets returned -- but I can see how that is more annoying to implement, and it probably doesn't really matter in practice, so this seems fine.

**Pull request merged**
