### PR TITLE
Fulfill AsyncPipe::tryPumpFrom() on EOF

### PR DESCRIPTION
**Pull request by harrishancock**
Previously if the input stream being pumped from encountered an EOF while the other side of the pipe was being pumped elsewhere, we did not fulfill the tryPumpFrom() promise, leaving it hanging.

### CODE REVIEW

**Comment by kentonv** [comment]
I don't think this is correct. `pumpTo()` is not supposed to propagate EOF. You can have two input streams and pump each of them, in sequence, to the same output stream.

So the outbound pump from a pipe should not complete just because an inbound pump to the pipe completed. There may be more subsequent inbound pumps coming. The outbound pump should only complete when the inbound side of the pipe is destroyed (which is, unfortunately, how we signal EOF at present).

**Comment by kentonv** [comment]
Actually I may have confused myself.

In your test, `pumpPromise` should complete but `pumpPromise2` should not, AFAICT. But I think your change affects only the first (making it correct), and the second may be a preexisting bug?

**Comment by harrishancock** [comment]
I concur -- it surprised me that `pumpPromise2` fulfilled earlier than I expected. I'm glad you read the test and confirmed.

I amended the commit and force-pushed to address the second bug.

**Comment by kentonv** [comment]
Awesome.

**Pull request merged**
