### PR TITLE
Revert "Merge pull request #1762 from capnproto/harris/kj-stack-array…

### PR DESCRIPTION
**Pull request by harrishancock**
…-no-longer-supports-vlas"

This reverts commit 15bcc0e55aec5b034e3736b098c5f2326e0a15a9, reversing changes made to 33991de6792fb9a96e46f632571106b2bbd23f8e.

### CODE REVIEW

**Comment by harrishancock** [comment]
PR #1762 appears to have caused a regression downstream in the Workers runtime, so I'm reverting it.

Note that this also reverts the Array destructor noexcept change, which we should probably reapply later.

**Comment by harrishancock** [comment]
I added a revert of https://github.com/capnproto/capnproto/pull/1774 due to downstream test failures it seems to have caused.

**Comment by harrishancock** [comment]
Also added a revert of https://github.com/capnproto/capnproto/pull/1786 due to an arm64-only downstream test failure it seems to have caused.

**Review by ohodson — APPROVED** [review]

**Comment by ohodson** [comment]
Approved assuming these are pure reverts.

**Pull request merged**
